module Elastics
  module ApiStubs

    # The following lines are autogenerated by Elastics.doc

    #  ########## Elastics.store ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  store:
    #  - PUT
    #  - "/<<index>>/<<type>>/<<id>>"
    #
    #
    #  Usage:
    #  Elastics.store :index => index,  # required
    #                 :type  => type,   # required
    #                 :id    => id      # required
    #
    def self.store(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :put_store


    #  ########## Elastics.post_store ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  post_store:
    #  - POST
    #  - "/<<index>>/<<type>>"
    #
    #
    #  Usage:
    #  Elastics.post_store :index => index,  # required
    #                      :type  => type    # required
    #
    def self.post_store(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get:
    #  - GET
    #  - "/<<index>>/<<type>>/<<id>>"
    #
    #
    #  Usage:
    #  Elastics.get :index => index,  # required
    #               :type  => type,   # required
    #               :id    => id      # required
    #
    def self.get(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_source ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_source:
    #  - GET
    #  - "/<<index>>/<<type>>/<<id>>/_source"
    #
    #
    #  Usage:
    #  Elastics.get_source :index => index,  # required
    #                      :type  => type,   # required
    #                      :id    => id      # required
    #
    def self.get_source(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.delete ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete:
    #  - DELETE
    #  - "/<<index>>/<<type>>/<<id>>"
    #
    #
    #  Usage:
    #  Elastics.delete :index => index,  # required
    #                  :type  => type,   # required
    #                  :id    => id      # required
    #
    def self.delete(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :remove


    #  ########## Elastics.update ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  update:
    #  - POST
    #  - "/<<index>>/<<type>>/<<id>>/_update"
    #
    #
    #  Usage:
    #  Elastics.update :index => index,  # required
    #                  :type  => type,   # required
    #                  :id    => id      # required
    #
    def self.update(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.multi_get_ids ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  multi_get_ids:
    #  - GET
    #  - "/<<index>>/<<type>>/_mget"
    #  - ids: "<< ids >>"
    #
    #
    #  Usage:
    #  Elastics.multi_get_ids :index => index,  # required
    #                         :type  => type,   # required
    #                         :ids   => ids     # required
    #
    def self.multi_get_ids(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :multi_get


    #  ########## Elastics.multi_get_docs ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  multi_get_docs:
    #  - GET
    #  - "/<<index= _all >>/<<type= ~ >>/_mget"
    #  - docs: "<< docs >>"
    #
    #
    #  Usage:
    #  Elastics.multi_get_docs :docs  => docs,   # required
    #                          :type  => nil,
    #                          :index => "_all"
    #
    def self.multi_get_docs(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.post_bulk_string ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  post_bulk_string:
    #  - POST
    #  - "/_bulk"
    #  - "<< bulk_string >>"
    #
    #
    #  Usage:
    #  Elastics.post_bulk_string :bulk_string => bulk_string  # required
    #
    def self.post_bulk_string(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :bulk


    #  ########## Elastics.termvector ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  termvector:
    #  - POST
    #  - "/<<index>>/<<type>>/<<id>>/_termvector"
    #
    #
    #  Usage:
    #  Elastics.termvector :index => index,  # required
    #                      :type  => type,   # required
    #                      :id    => id      # required
    #
    def self.termvector(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.multi_termvectors ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  multi_termvectors:
    #  - POST
    #  - "/<<index>>/<<type>>/_mtermvectors"
    #  - docs: "<<docs= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.multi_termvectors :index => index,  # required
    #                             :type  => type,   # required
    #                             :docs  => nil
    #
    def self.multi_termvectors(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.search_shards ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  search_shards:
    #  - GET
    #  - "/<<index= _all >>/<<type= ~ >>/_search_shards"
    #
    #
    #  Usage:
    #  Elastics.search_shards :index => "_all",
    #                         :type  => nil
    #
    def self.search_shards(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.count ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  count:
    #  - GET
    #  - "/<<index= _all >>/<<type= ~ >>/_count"
    #
    #
    #  Usage:
    #  Elastics.count :index => "_all",
    #                 :type  => nil
    #
    def self.count(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.search_exists ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  search_exists:
    #  - GET
    #  - "/<<index= _all >>/<<type= ~ >>/<<id= ~ >>/_search/exists"
    #
    #
    #  Usage:
    #  Elastics.search_exists :index => "_all",
    #                         :type  => nil,
    #                         :id    => nil
    #
    def self.search_exists(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.validate ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  validate:
    #  - GET
    #  - "/<<index= _all >>/<<type= ~ >>/<<id= ~ >>/_validate/query"
    #
    #
    #  Usage:
    #  Elastics.validate :index => "_all",
    #                    :type  => nil,
    #                    :id    => nil
    #
    def self.validate(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.explain ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  explain:
    #  - GET
    #  - "/<<index= _all >>/<<type= ~ >>/<<id= ~ >>/_explain"
    #
    #
    #  Usage:
    #  Elastics.explain :index => "_all",
    #                   :type  => nil,
    #                   :id    => nil
    #
    def self.explain(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.percolate ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  percolate:
    #  - GET
    #  - "/<<index>>/<<type>>/_percolate"
    #
    #
    #  Usage:
    #  Elastics.percolate :index => index,  # required
    #                     :type  => type    # required
    #
    def self.percolate(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.percolate_count ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  percolate_count:
    #  - GET
    #  - "/<<index>>/<<type>>/_percolate/count"
    #
    #
    #  Usage:
    #  Elastics.percolate_count :index => index,  # required
    #                           :type  => type    # required
    #
    def self.percolate_count(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.put_percolator ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_percolator:
    #  - PUT
    #  - "/<<index>>/.percolator/<<id>>"
    #
    #
    #  Usage:
    #  Elastics.put_percolator :index => index,  # required
    #                          :id    => id      # required
    #
    def self.put_percolator(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.delete_percolator ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete_percolator:
    #  - DELETE
    #  - "/<<index>>/.percolator/<<id>>"
    #
    #
    #  Usage:
    #  Elastics.delete_percolator :index => index,  # required
    #                             :id    => id      # required
    #
    def self.delete_percolator(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.more_like_this ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  more_like_this:
    #  - GET
    #  - "/<<index>>/<<type>>/<<id>>/_mlt"
    #
    #
    #  Usage:
    #  Elastics.more_like_this :index => index,  # required
    #                          :type  => type,   # required
    #                          :id    => id      # required
    #
    def self.more_like_this(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :mlt


    #  ########## Elastics.put_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_index:
    #  - PUT
    #  - "/<<index>>"
    #  - settings:
    #      number_of_shards: "<<number_of_shards= 5 >>"
    #      number_of_replicas: "<<number_of_replicas= 1 >>"
    #
    #
    #  Usage:
    #  Elastics.put_index :index              => index,  # required
    #                     :number_of_shards   => 5,
    #                     :number_of_replicas => 1
    #
    def self.put_index(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :create_index


    #  ########## Elastics.post_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  post_index:
    #  - POST
    #  - "/<<index>>"
    #  - settings:
    #      number_of_shards: "<<number_of_shards= 5 >>"
    #      number_of_replicas: "<<number_of_replicas= 1 >>"
    #
    #
    #  Usage:
    #  Elastics.post_index :index              => index,  # required
    #                      :number_of_shards   => 5,
    #                      :number_of_replicas => 1
    #
    def self.post_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.delete_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete_index:
    #  - DELETE
    #  - "/<<index>>"
    #
    #
    #  Usage:
    #  Elastics.delete_index :index => index  # required
    #
    def self.delete_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index:
    #  - GET
    #  - "/<<index>>/<<features= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.get_index :index    => index,  # required
    #                     :features => nil
    #
    def self.get_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.indices_exists ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  indices_exists:
    #  - HEAD
    #  - "/<<index>>"
    #
    #
    #  Usage:
    #  Elastics.indices_exists :index => index  # required
    #
    def self.indices_exists(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :index_exists, :exist?


    #  ########## Elastics.close_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  close_index:
    #  - POST
    #  - "/<<index>>/_close"
    #
    #
    #  Usage:
    #  Elastics.close_index :index => index  # required
    #
    def self.close_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.open_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  open_index:
    #  - POST
    #  - "/<<index>>/_open"
    #
    #
    #  Usage:
    #  Elastics.open_index :index => index  # required
    #
    def self.open_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.put_index_mapping ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_index_mapping:
    #  - PUT
    #  - "/<<index>>/_mapping/<<type>>"
    #  - "<<type>>":
    #      properties: "<<properties>>"
    #
    #
    #  Usage:
    #  Elastics.put_index_mapping :index      => index,      # required
    #                             :type       => type,       # required
    #                             :properties => properties  # required
    #
    def self.put_index_mapping(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :put_mapping


    #  ########## Elastics.get_index_mapping ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index_mapping:
    #  - GET
    #  - "/<<index= _all >>/_mapping/<<type= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.get_index_mapping :index => "_all",
    #                             :type  => nil
    #
    def self.get_index_mapping(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_field_mapping ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_field_mapping:
    #  - GET
    #  - "/<<index>>/_mapping/<<type>>/field/<<field>>"
    #
    #
    #  Usage:
    #  Elastics.get_field_mapping :index => index,  # required
    #                             :type  => type,   # required
    #                             :field => field   # required
    #
    def self.get_field_mapping(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.types_exists ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  types_exists:
    #  - HEAD
    #  - "/<<index>>/<<type>>"
    #
    #
    #  Usage:
    #  Elastics.types_exists :index => index,  # required
    #                        :type  => type    # required
    #
    def self.types_exists(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :type_exists


    #  ########## Elastics.delete_index_mapping ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete_index_mapping:
    #  - DELETE
    #  - "/<<index>>/<<type>>"
    #
    #
    #  Usage:
    #  Elastics.delete_index_mapping :index => index,  # required
    #                                :type  => type    # required
    #
    def self.delete_index_mapping(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.post_index_aliases ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  post_index_aliases:
    #  - POST
    #  - "/_aliases"
    #  - actions: "<<actions>>"
    #
    #
    #  Usage:
    #  Elastics.post_index_aliases :actions => actions  # required
    #
    def self.post_index_aliases(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_index_aliases ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index_aliases:
    #  - GET
    #  - "/<<index>>/_aliases"
    #
    #
    #  Usage:
    #  Elastics.get_index_aliases :index => index  # required
    #
    def self.get_index_aliases(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.put_index_alias ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_index_alias:
    #  - PUT
    #  - "/<<index>>/_alias/<<alias>>"
    #
    #
    #  Usage:
    #  Elastics.put_index_alias :index => index,  # required
    #                           :alias => alias   # required
    #
    def self.put_index_alias(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.delete_index_alias ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete_index_alias:
    #  - DELETE
    #  - "/<<index>>/_alias/<<alias>>"
    #
    #
    #  Usage:
    #  Elastics.delete_index_alias :index => index,  # required
    #                              :alias => alias   # required
    #
    def self.delete_index_alias(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_index_alias ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index_alias:
    #  - GET
    #  - "/<<index= _all >>/_alias/<<alias= '*' >>"
    #
    #
    #  Usage:
    #  Elastics.get_index_alias :index => "_all",
    #                           :alias => "*"
    #
    def self.get_index_alias(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.update_index_settings ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  update_index_settings:
    #  - PUT
    #  - "/<<index= _all >>/_settings"
    #
    #
    #  Usage:
    #  Elastics.update_index_settings :index => "_all"
    #
    def self.update_index_settings(*vars)
      ## this is a stub, used for reference
      super
    end
    # also aliased by: :put_index_settings


    #  ########## Elastics.get_index_settings ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index_settings:
    #  - GET
    #  - "/<<index>>/_settings"
    #
    #
    #  Usage:
    #  Elastics.get_index_settings :index => index  # required
    #
    def self.get_index_settings(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_settings ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_settings:
    #  - GET
    #  - "/<<index>>/_settings"
    #
    #
    #  Usage:
    #  Elastics.get_settings :index => index  # required
    #
    def self.get_settings(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.analyze_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  analyze_index:
    #  - GET
    #  - "/<<index= _all >>/_analyze"
    #
    #
    #  Usage:
    #  Elastics.analyze_index :index => "_all"
    #
    def self.analyze_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.put_index_template ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_index_template:
    #  - PUT
    #  - "/_template/<<template>>"
    #
    #
    #  Usage:
    #  Elastics.put_index_template :template => template  # required
    #
    def self.put_index_template(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.delete_index_template ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete_index_template:
    #  - DELETE
    #  - "/_template/<<template>>"
    #
    #
    #  Usage:
    #  Elastics.delete_index_template :template => template  # required
    #
    def self.delete_index_template(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_index_template ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index_template:
    #  - GET
    #  - "/_template/<<template= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.get_index_template :template => nil
    #
    def self.get_index_template(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.index_template_exists ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  index_template_exists:
    #  - HEAD
    #  - "/_template/<<template>>"
    #
    #
    #  Usage:
    #  Elastics.index_template_exists :template => template  # required
    #
    def self.index_template_exists(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.put_index_warmer ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_index_warmer:
    #  - PUT
    #  - "/<<index= _all >>/<<type= ~ >>/_warmer/<<warmer>>"
    #
    #
    #  Usage:
    #  Elastics.put_index_warmer :warmer => warmer,  # required
    #                            :type   => nil,
    #                            :index  => "_all"
    #
    def self.put_index_warmer(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.delete_index_warmer ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  delete_index_warmer:
    #  - DELETE
    #  - "/<<index>>/_warmer/<<warmer>>"
    #
    #
    #  Usage:
    #  Elastics.delete_index_warmer :index  => index,  # required
    #                               :warmer => warmer  # required
    #
    def self.delete_index_warmer(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_index_warmer ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_index_warmer:
    #  - GET
    #  - "/<<index>>/_warmer/<<warmer= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.get_index_warmer :index  => index,  # required
    #                            :warmer => nil
    #
    def self.get_index_warmer(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.index_status ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  index_status:
    #  - GET
    #  - "/<<index= _all >>/_status"
    #
    #
    #  Usage:
    #  Elastics.index_status :index => "_all"
    #
    def self.index_status(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.index_stats ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  index_stats:
    #  - GET
    #  - "/<<index= _all >>/_stats/<<stats= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.index_stats :index => "_all",
    #                       :stats => nil
    #
    def self.index_stats(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.index_segments ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  index_segments:
    #  - GET
    #  - "/<<index= _all >>/_segments"
    #
    #
    #  Usage:
    #  Elastics.index_segments :index => "_all"
    #
    def self.index_segments(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.index_recovery ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  index_recovery:
    #  - GET
    #  - "/<<index= _all >>/_recovery"
    #
    #
    #  Usage:
    #  Elastics.index_recovery :index => "_all"
    #
    def self.index_recovery(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.index_clearcache ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  index_clearcache:
    #  - POST
    #  - "/<<index= _all >>/_cache/clear"
    #
    #
    #  Usage:
    #  Elastics.index_clearcache :index => "_all"
    #
    def self.index_clearcache(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.flush_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  flush_index:
    #  - POST
    #  - "/<<index= _all >>/_flush"
    #
    #
    #  Usage:
    #  Elastics.flush_index :index => "_all"
    #
    def self.flush_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.synced_flush_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  synced_flush_index:
    #  - POST
    #  - "/<<index= _all >>/_flush/synced"
    #
    #
    #  Usage:
    #  Elastics.synced_flush_index :index => "_all"
    #
    def self.synced_flush_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.refresh_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  refresh_index:
    #  - POST
    #  - "/<<index= _all >>/_refresh"
    #
    #
    #  Usage:
    #  Elastics.refresh_index :index => "_all"
    #
    def self.refresh_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.optimize_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  optimize_index:
    #  - POST
    #  - "/<<index= _all >>/_optimize"
    #
    #
    #  Usage:
    #  Elastics.optimize_index :index => "_all"
    #
    def self.optimize_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.upgrade_index ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  upgrade_index:
    #  - POST
    #  - "/<<index>>/_upgrade"
    #
    #
    #  Usage:
    #  Elastics.upgrade_index :index => index  # required
    #
    def self.upgrade_index(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_health ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_health:
    #  - GET
    #  - "/_cluster/health/<<index= _all >>"
    #
    #
    #  Usage:
    #  Elastics.cluster_health :index => "_all"
    #
    def self.cluster_health(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_state ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_state:
    #  - GET
    #  - "/_cluster/state/<<metrics= _all >>/<<index= _all >>"
    #
    #
    #  Usage:
    #  Elastics.cluster_state :metrics => "_all",
    #                         :index   => "_all"
    #
    def self.cluster_state(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_stats ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_stats:
    #  - GET
    #  - "/_cluster/stats"
    #
    #
    #  Usage:
    #  Elastics.cluster_stats
    #
    def self.cluster_stats(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_pending_tasks ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_pending_tasks:
    #  - GET
    #  - "/_cluster/pending_tasks"
    #
    #
    #  Usage:
    #  Elastics.cluster_pending_tasks
    #
    def self.cluster_pending_tasks(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_reroute ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_reroute:
    #  - POST
    #  - "/_cluster/reroute"
    #
    #
    #  Usage:
    #  Elastics.cluster_reroute
    #
    def self.cluster_reroute(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.put_cluster_settings ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  put_cluster_settings:
    #  - PUT
    #  - "/_cluster/settings"
    #
    #
    #  Usage:
    #  Elastics.put_cluster_settings
    #
    def self.put_cluster_settings(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.get_cluster_settings ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  get_cluster_settings:
    #  - GET
    #  - "/_cluster/settings"
    #
    #
    #  Usage:
    #  Elastics.get_cluster_settings
    #
    def self.get_cluster_settings(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_nodes_stats ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_stats:
    #  - GET
    #  - "/_nodes/<<nodes= ~ >>/stats/<<stats= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_stats :nodes => nil,
    #                               :stats => nil
    #
    def self.cluster_nodes_stats(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_nodes_info ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_info:
    #  - GET
    #  - "/_nodes/<<nodes= ~ >>/<<info= ~ >>"
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_info :nodes => nil,
    #                              :info  => nil
    #
    def self.cluster_nodes_info(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.cluster_nodes_hot_threads ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_hot_threads:
    #  - GET
    #  - "/_nodes/<<nodes= ~ >>/hot_threads"
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_hot_threads :nodes => nil
    #
    def self.cluster_nodes_hot_threads(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.match_all ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  match_all:
    #  - GET
    #  - "/<<index>>/<<type>>/_search"
    #  - query:
    #      match_all: {}
    #
    #
    #  Usage:
    #  Elastics.match_all :index => index,  # required
    #                     :type  => type    # required
    #
    def self.match_all(*vars)
      ## this is a stub, used for reference
      super
    end


    #  ########## Elastics.search_by_id ##########
    #  ------------------
    #  Elastics::Template
    #  ---
    #  search_by_id:
    #  - GET
    #  - "/<<index>>/<<type>>/_search"
    #  - query:
    #      term:
    #        _id: "<<id>>"
    #
    #
    #  Usage:
    #  Elastics.search_by_id :index => index,  # required
    #                        :type  => type,   # required
    #                        :id    => id      # required
    #
    def self.search_by_id(*vars)
      ## this is a stub, used for reference
      super
    end

  end
end
