module Elastics
  module ApiStubs

    # The following lines are autogenerated by Elastics.doc

    ######################## Core API ########################

    #  ########## Elastics.store ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  store:
    #  - PUT
    #  - /<<index>>/<<type>>/<<id>>
    #
    #
    #  Usage:
    #  Elastics.store :id    => id,    # required
    #                 :type  => nil,
    #                 :index => "elastics_test_index"
    #
    def Elastics.store(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_store ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_store:
    #  - PUT
    #  - /<<index>>/<<type>>/<<id>>
    #
    #
    #  Usage:
    #  Elastics.put_store :id    => id,    # required
    #                     :type  => nil,
    #                     :index => "elastics_test_index"
    #
    def Elastics.put_store(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.post_store ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  post_store:
    #  - POST
    #  - /<<index>>/<<type>>
    #
    #
    #  Usage:
    #  Elastics.post_store :index => "elastics_test_index",
    #                      :type  => nil
    #
    def Elastics.post_store(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete:
    #  - DELETE
    #  - /<<index>>/<<type>>/<<id>>
    #
    #
    #  Usage:
    #  Elastics.delete :id    => id,    # required
    #                  :type  => nil,
    #                  :index => "elastics_test_index"
    #
    def Elastics.delete(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.remove ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  remove:
    #  - DELETE
    #  - /<<index>>/<<type>>/<<id>>
    #
    #
    #  Usage:
    #  Elastics.remove :id    => id,    # required
    #                  :type  => nil,
    #                  :index => "elastics_test_index"
    #
    def Elastics.remove(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get:
    #  - GET
    #  - /<<index>>/<<type>>/<<id>>
    #
    #
    #  Usage:
    #  Elastics.get :id    => id,    # required
    #               :type  => nil,
    #               :index => "elastics_test_index"
    #
    def Elastics.get(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_source ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_source:
    #  - GET
    #  - /<<index>>/<<type>>/<<id>>/_source
    #
    #
    #  Usage:
    #  Elastics.get_source :id    => id,    # required
    #                      :type  => nil,
    #                      :index => "elastics_test_index"
    #
    def Elastics.get_source(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.multi_get ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  multi_get:
    #  - GET
    #  - /<<index>>/<<type>>/_mget
    #  - ids: << ids >>
    #
    #
    #  Usage:
    #  Elastics.multi_get :ids   => ids,   # required
    #                     :type  => nil,
    #                     :index => "elastics_test_index"
    #
    def Elastics.multi_get(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.update ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  update:
    #  - POST
    #  - /<<index>>/<<type>>/<<id>>/_update
    #
    #
    #  Usage:
    #  Elastics.update :id    => id,    # required
    #                  :type  => nil,
    #                  :index => "elastics_test_index"
    #
    def Elastics.update(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.percolate ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  percolate:
    #  - GET
    #  - /<<index>>/<<type>>/_percolate
    #
    #
    #  Usage:
    #  Elastics.percolate :index => "elastics_test_index",
    #                     :type  => nil
    #
    def Elastics.percolate(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_percolator ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_percolator:
    #  - PUT
    #  - /_percolator/<<index>>/<<percolator>>
    #
    #
    #  Usage:
    #  Elastics.put_percolator :percolator => percolator,  # required
    #                          :index      => "elastics_test_index"
    #
    def Elastics.put_percolator(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_percolator ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_percolator:
    #  - DELETE
    #  - /_percolator/<<index>>/<<percolator>>
    #
    #
    #  Usage:
    #  Elastics.delete_percolator :percolator => percolator,  # required
    #                             :index      => "elastics_test_index"
    #
    def Elastics.delete_percolator(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.post_bulk_string ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  post_bulk_string:
    #  - POST
    #  - /_bulk
    #  - << bulk_string >>
    #
    #
    #  Usage:
    #  Elastics.bulk :bulk_string => bulk_string  # required
    #
    def Elastics.post_bulk_string(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.count ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  count:
    #  - GET
    #  - /<<index>>/<<type>>/_count
    #
    #
    #  Usage:
    #  Elastics.count :index => "elastics_test_index",
    #                 :type  => nil
    #
    def Elastics.count(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_by_query ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_by_query:
    #  - DELETE
    #  - /<<index>>/<<type>>/_query
    #
    #
    #  Usage:
    #  Elastics.delete_by_query :index => "elastics_test_index",
     #                          :type  => nil
    #
    def Elastics.delete_by_query(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.more_like_this ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  more_like_this:
    #  - GET
    #  - /<<index>>/<<type>>/<<id>>/_mlt
    #
    #
    #  Usage:
    #  Elastics.more_like_this :id    => id,    # required
    #                          :type  => nil,
    #                          :index => "elastics_test_index"
    #
    def Elastics.more_like_this(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.mlt ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  mlt:
    #  - GET
    #  - /<<index>>/<<type>>/<<id>>/_mlt
    #
    #
    #  Usage:
    #  Elastics.mlt :id    => id,    # required
    #               :type  => nil,
    #               :index => "elastics_test_index"
    #
    def Elastics.mlt(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.validate ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  validate:
    #  - GET
    #  - /<<index>>/<<type>>/_validate/query
    #
    #
    #  Usage:
    #  Elastics.validate :index => "elastics_test_index",
    #                    :type  => nil
    #
    def Elastics.validate(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.explain ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  explain:
    #  - GET
    #  - /<<index>>/<<type>>/<<id>>/_explain
    #
    #
    #  Usage:
    #  Elastics.explain :id    => id,    # required
    #                   :type  => nil,
    #                   :index => "elastics_test_index"
    #
    def Elastics.explain(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.match_all ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  match_all:
    #  - GET
    #  - /<<index>>/<<type>>/_search
    #  - query:
    #      match_all: {}
    #
    #
    #  Usage:
    #  Elastics.match_all :index => "elastics_test_index",
    #                     :type  => nil
    #
    def Elastics.match_all(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.search_by_id ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  search_by_id:
    #  - GET
    #  - /<<index>>/<<type>>/_search
    #  - query:
    #      term:
    #        _id: <<id>>
    #
    #
    #  Usage:
    #  Elastics.search_by_id :id      => id,    # required
    #                        :type    => nil,
    #                        :index   => "elastics_test_index",
    #
    def Elastics.search_by_id(*vars)
      ## this is a stub, used for reference
      super
    end

    ######################## Indices API ########################

    #  ########## Elastics.post_index_aliases ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  post_index_aliases:
    #  - POST
    #  - /_aliases
    #
    #
    #  Usage:
    #  Elastics.post_index_aliases
    #
    def Elastics.post_index_aliases(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_index_aliases ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_index_aliases:
    #  - GET
    #  - /<<index>>/_aliases
    #
    #
    #  Usage:
    #  Elastics.get_index_aliases :index => "elastics_test_index"
    #
    def Elastics.get_index_aliases(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.add_index_alias ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  add_index_alias:
    #  - PUT
    #  - /<<index>>/_alias/<<alias>>
    #
    #
    #  Usage:
    #  Elastics.add_index_alias :alias => alias,  # required
    #                           :index => "elastics_test_index"
    #
    def Elastics.add_index_alias(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_index_alias ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_index_alias:
    #  - DELETE
    #  - /<<index>>/_alias/<<alias>>
    #
    #
    #  Usage:
    #  Elastics.delete_index_alias :alias => alias,  # required
    #                              :index => "elastics_test_index"
    #
    def Elastics.delete_index_alias(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_index_alias ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_index_alias:
    #  - GET
    #  - /<<index>>/_alias/<<alias= '*' >>
    #
    #
    #  Usage:
    #  Elastics.get_index_alias :index => "elastics_test_index",
    #                           :alias => "*"
    #
    def Elastics.get_index_alias(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.analyze_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  analyze_index:
    #  - GET
    #  - /<<index>>/_analyze
    #
    #
    #  Usage:
    #  Elastics.analyze_index :index => "elastics_test_index"
    #
    def Elastics.analyze_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_index:
    #  - PUT
    #  - /<<index>>
    #  - settings:
    #      number_of_shards: <<number_of_shards= 5 >>
    #      number_of_replicas: <<number_of_replicas= 1 >>
    #
    #
    #  Usage:
    #  Elastics.put_index :index              => "elastics_test_index",
    #                     :number_of_shards   => 5,
    #                     :number_of_replicas => 1
    #
    def Elastics.put_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.create_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  create_index:
    #  - PUT
    #  - /<<index>>
    #  - settings:
    #      number_of_shards: <<number_of_shards= 5 >>
    #      number_of_replicas: <<number_of_replicas= 1 >>
    #
    #
    #  Usage:
    #  Elastics.create_index :index              => "elastics_test_index",
    #                        :number_of_shards   => 5,
    #                        :number_of_replicas => 1
    #
    def Elastics.create_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.post_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  post_index:
    #  - POST
    #  - /<<index>>
    #  - settings:
    #      number_of_shards: <<number_of_shards= 5 >>
    #      number_of_replicas: <<number_of_replicas= 1 >>
    #
    #
    #  Usage:
    #  Elastics.post_index :index              => "elastics_test_index",
    #                      :number_of_shards   => 5,
    #                      :number_of_replicas => 1
    #
    def Elastics.post_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_index:
    #  - DELETE
    #  - /<<index>>
    #
    #
    #  Usage:
    #  Elastics.delete_index :index => "elastics_test_index"
    #
    def Elastics.delete_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.close_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  close_index:
    #  - POST
    #  - /<<index>>/_close
    #
    #
    #  Usage:
    #  Elastics.close_index :index => "elastics_test_index"
    #
    def Elastics.close_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.open_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  open_index:
    #  - POST
    #  - /<<index>>/_close
    #
    #
    #  Usage:
    #  Elastics.open_index :index => "elastics_test_index"
    #
    def Elastics.open_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_index_settings ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_index_settings:
    #  - GET
    #  - /<<index>>/_settings
    #
    #
    #  Usage:
    #  Elastics.get_index_settings :index => "elastics_test_index"
    #
    def Elastics.get_index_settings(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_settings ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_settings:
    #  - GET
    #  - /<<index>>/_settings
    #
    #
    #  Usage:
    #  Elastics.get_settings :index => "elastics_test_index"
    #
    def Elastics.get_settings(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_index_mapping ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_index_mapping:
    #  - GET
    #  - /<<index>>/<<type>>/_mapping
    #
    #
    #  Usage:
    #  Elastics.get_index_mapping :index => "elastics_test_index",
    #                             :type  => nil
    #
    def Elastics.get_index_mapping(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_mapping ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_mapping:
    #  - GET
    #  - /<<index>>/<<type>>/_mapping
    #
    #
    #  Usage:
    #  Elastics.get_mapping :index => "elastics_test_index",
    #                       :type  => nil
    #
    def Elastics.get_mapping(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_index_mapping ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_index_mapping:
    #  - PUT
    #  - /<<index>>/<<type>>/_mapping
    #  - <<type>>:
    #      properties: <<properties>>
    #
    #
    #  Usage:
    #  Elastics.put_index_mapping :properties => properties,  # required
    #                             :type       => nil,
    #                             :index      => "elastics_test_index"
    #
    def Elastics.put_index_mapping(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_mapping ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_mapping:
    #  - PUT
    #  - /<<index>>/<<type>>/_mapping
    #  - <<type>>:
    #      properties: <<properties>>
    #
    #
    #  Usage:
    #  Elastics.put_mapping :properties => properties,  # required
    #                       :type       => nil,
    #                       :index      => "elastics_test_index"
    #
    def Elastics.put_mapping(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_index_mapping ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_index_mapping:
    #  - DELETE
    #  - /<<index>>/<<type>>
    #
    #
    #  Usage:
    #  Elastics.delete_index_mapping :index => "elastics_test_index",
    #                                :type  => nil
    #
    def Elastics.delete_index_mapping(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_mapping ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_mapping:
    #  - DELETE
    #  - /<<index>>/<<type>>
    #
    #
    #  Usage:
    #  Elastics.delete_mapping :index => "elastics_test_index",
    #                          :type  => nil
    #
    def Elastics.delete_mapping(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.refresh_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  refresh_index:
    #  - POST
    #  - /<<index>>/_refresh
    #
    #
    #  Usage:
    #  Elastics.refresh_index :index => "elastics_test_index"
    #
    def Elastics.refresh_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.optimize_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  optimize_index:
    #  - POST
    #  - /<<index>>/_optimize
    #
    #
    #  Usage:
    #  Elastics.optimize_index :index => "elastics_test_index"
    #
    def Elastics.optimize_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.flush_index ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  flush_index:
    #  - POST
    #  - /<<index>>/_flush
    #
    #
    #  Usage:
    #  Elastics.flush_index :index => "elastics_test_index"
    #
    def Elastics.flush_index(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.gateway_snapshot ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  gateway_snapshot:
    #  - POST
    #  - /<<index>>/_gateway/snapshot
    #
    #
    #  Usage:
    #  Elastics.gateway_snapshot :index => "elastics_test_index"
    #
    def Elastics.gateway_snapshot(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.update_index_settings ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  update_index_settings:
    #  - PUT
    #  - /<<index>>/_settings
    #
    #
    #  Usage:
    #  Elastics.update_index_settings :index => "elastics_test_index"
    #
    def Elastics.update_index_settings(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_index_template ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_index_template:
    #  - PUT
    #  - /_template/<<template>>
    #
    #
    #  Usage:
    #  Elastics.put_index_template :template => template  # required
    #
    def Elastics.put_index_template(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_index_template ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_index_template:
    #  - DELETE
    #  - /_template/<<template>>
    #
    #
    #  Usage:
    #  Elastics.delete_index_template :template => template  # required
    #
    def Elastics.delete_index_template(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_index_template ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_index_template:
    #  - GET
    #  - /_template/<<template>>
    #
    #
    #  Usage:
    #  Elastics.get_index_template :template => template  # required
    #
    def Elastics.get_index_template(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_index_warmer ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_index_warmer:
    #  - PUT
    #  - /<<index>>/<<type>>/_warmer/<<warmer>>
    #
    #
    #  Usage:
    #  Elastics.put_index_warmer :warmer => warmer,  # required
    #                            :type   => nil,
    #                            :index  => "elastics_test_index"
    #
    def Elastics.put_index_warmer(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.delete_index_warmer ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  delete_index_warmer:
    #  - DELETE
    #  - /<<index>>/_warmer/<<warmer= ~ >>
    #
    #
    #  Usage:
    #  Elastics.delete_index_warmer :index  => "elastics_test_index",
    #                               :warmer => nil
    #
    def Elastics.delete_index_warmer(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_index_warmer ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_index_warmer:
    #  - GET
    #  - /<<index>>/_warmer/<<warmer= ~ >>
    #
    #
    #  Usage:
    #  Elastics.get_index_warmer :index  => "elastics_test_index",
    #                            :warmer => nil
    #
    def Elastics.get_index_warmer(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.index_stats ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  index_stats:
    #  - GET
    #  - /<<index>>/_stats/<<endpoint= ~ >>/<<names= ~ >>
    #
    #
    #  Usage:
    #  Elastics.index_stats :index    => "elastics_test_index",
    #                       :endpoint => nil,
    #                       :names    => nil
    #
    def Elastics.index_stats(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.stats ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  stats:
    #  - GET
    #  - /<<index>>/_stats/<<endpoint= ~ >>/<<names= ~ >>
    #
    #
    #  Usage:
    #  Elastics.stats :index    => "elastics_test_index",
    #                 :endpoint => nil,
    #                 :names    => nil
    #
    def Elastics.stats(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.index_status ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  index_status:
    #  - GET
    #  - /<<index>>/_status
    #
    #
    #  Usage:
    #  Elastics.index_status :index => "elastics_test_index"
    #
    def Elastics.index_status(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.index_segments ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  index_segments:
    #  - GET
    #  - /<<index>>/_segments
    #
    #
    #  Usage:
    #  Elastics.index_segments :index => "elastics_test_index"
    #
    def Elastics.index_segments(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.index_clearcache ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  index_clearcache:
    #  - POST
    #  - /<<index>>/_cache/clear
    #
    #
    #  Usage:
    #  Elastics.index_clearcache :index => "elastics_test_index"
    #
    def Elastics.index_clearcache(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.indices_exists ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  indices_exists:
    #  - HEAD
    #  - /<<index>>
    #
    #
    #  Usage:
    #  Elastics.indices_exists :index => "elastics_test_index"
    #
    def Elastics.indices_exists(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.exist? ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  exist?:
    #  - HEAD
    #  - /<<index>>
    #
    #
    #  Usage:
    #  Elastics.exist? :index => "elastics_test_index"
    #
    def Elastics.exist?(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.types_exists ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  types_exists:
    #  - HEAD
    #  - /<<index>>/<<type>>
    #
    #
    #  Usage:
    #  Elastics.types_exists :index => "elastics_test_index",
    #                        :type  => nil
    #
    def Elastics.types_exists(*vars)
      ## this is a stub, used for reference
      super
    end


    ######################## Cluster API ########################

    #  ########## Elastics.cluster_health ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_health:
    #  - GET
    #  - /_cluster/health/<<index>>
    #
    #
    #  Usage:
    #  Elastics.cluster_health :index => "elastics_test_index"
    #
    def Elastics.cluster_health(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.cluster_state ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_state:
    #  - GET
    #  - /_cluster/state
    #
    #
    #  Usage:
    #  Elastics.cluster_state
    #
    def Elastics.cluster_state(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.put_cluster_settings ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  put_cluster_settings:
    #  - PUT
    #  - /_cluster/settings
    #
    #
    #  Usage:
    #  Elastics.put_cluster_settings
    #
    def Elastics.put_cluster_settings(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.get_cluster_settings ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  get_cluster_settings:
    #  - GET
    #  - /_cluster/settings
    #
    #
    #  Usage:
    #  Elastics.get_cluster_settings
    #
    def Elastics.get_cluster_settings(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.cluster_nodes_info ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_info:
    #  - GET
    #  - /_nodes/<<nodes= ~ >>/<<endpoint= ~ >>
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_info :nodes    => nil,
    #                              :endpoint => nil
    #
    def Elastics.cluster_nodes_info(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.cluster_nodes_stats ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_stats:
    #  - GET
    #  - /_nodes/<<nodes= ~ >>/stats/<<endpoint= ~ >>
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_stats :nodes    => nil,
    #                               :endpoint => nil
    #
    def Elastics.cluster_nodes_stats(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.cluster_nodes_shutdown ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_shutdown:
    #  - POST
    #  - /_cluster/nodes/<<nodes= ~ >>/_shutdown
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_shutdown :nodes => nil
    #
    def Elastics.cluster_nodes_shutdown(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.cluster_nodes_hot_threads ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_nodes_hot_threads:
    #  - GET
    #  - /_nodes/<<nodes= ~ >>/hot_threads
    #
    #
    #  Usage:
    #  Elastics.cluster_nodes_hot_threads :nodes => nil
    #
    def Elastics.cluster_nodes_hot_threads(*vars)
      ## this is a stub, used for reference
      super
    end

    #  ########## Elastics.cluster_reroute ##########
    #  --------------
    #  Elastics::Template
    #  ---
    #  cluster_reroute:
    #  - POST
    #  - /_cluster/reroute
    #
    #
    #  Usage:
    #  Elastics.cluster_reroute
    #
    def Elastics.cluster_reroute(*vars)
      ## this is a stub, used for reference
      super
    end


  end
end
